#ifndef _COMM_TESTER_RX_FRAME_H
#define _COMM_TESTER_RX_FRAME_H

#include "includes.h"

#define COMTEST_RX_COMMAND_1_LOAD (0x01)
#define COMTEST_RX_COMMAND_1_READLOAD (0x02)
#define COMTEST_RX_COMMAND_1_WIFI (0x03)
#define COMTEST_RX_COMMAND_1_SN (0x88)
#define COMTEST_RX_COMMAND_1_IAP (0xAA)

#define VALVECLOSE (0x00)
#define VALVEOPEN (0x01)
#define OUTOFCOLDWATER (0x01)
#define OUTOFSPARKLINGWATER (0x02)
#define OUTOFCOOLWATER (0x03)
#define ADDOFCOOLWATER (0x04)
#define PROFITEERINGADDWATER (0x05)
#define BOOSTERPUMP (0x06)
#define MIXMOTOR (0x07)
#define FANMOTOR (0x08)
#define COMPRESSOR (0x09)
#define CLOSEALLLOAD (0x10)

#define READOUTOFCOLDWATERCURRENT (0x01)
#define READOUTOFSPARKLINGWATERCURRENT (0x02)
#define READOUTOFCOOLWATERCURRENT (0x03)
#define READADDOFCOOLWATERCURRENT (0x04)
#define READPROFITEERINGADDWATERCURRENT (0x05)
#define READBOOSTERPUMPCURRENT (0x06)
#define READFANMOTORCURRENT (0x08)
#define READMIXMOTORCURRENT (0X07)
#define READCOLDWATERBOXTEMP1 (0x0C)
#define READCOLDWATERBOXTEMP2 (0x0D)
#define READCARBONATIONTANKHIGHWATERLEVEL (0x0E)
#define READCARBONATIONTANKLOWWATERLEVEL (0x0F)

void CommTester_Rx_Frame_Analyize();

#endif
